site_name: Academic Reading and Writing
site_url: https://concinna.github.io/arw/
copyright: Atheris hispida
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
  - navigation.tracking
  - navigation.footer
  - navigation.expand
  - search.highlight
  - search.suggest
  - content.code.copy
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/marked/marked.min.js
  - https://cdn.jsdelivr.net/npm/dompurify/dist/purify.min.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

nav:
  - Week 1:
    - 'Intro Course requirement': 'index.md'
    - 'Thesis Research': 'Week1_2_ThesisResearchnew.md'
    - 'Uncomfortable Talk': 'Week1_3_UncomfortableTalk.md'
  - Week 2:
    - 'Box3 Research topics': 'Week2_1_Box3 Research topics.md'
    - 'How to develop RQ': 'Week2_1_How to develop RQ_new.md'
    - 'Data sources': 'Week2_2_Data sources_new.md'
  - Week 3:
    - 'Literature search': 'Week3_1&2_Literature search new.md'
    - 'Literature reading': 'Week3_3_literature reading.md'
  - Week 4:
    - 'Literature review': 'Week4_1_Literature review_new1.md'
  - 'Syllabus': '英文教学大纲2025.md'

